# Generated by Django 3.0.7 on 2020-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abv', models.CharField(default='', max_length=3)),
                ('rate', models.FloatField()),
                ('rev_rate', models.FloatField(default=0)),
            ],
        ),
    ]
